# Generated by Django 3.2.4 on 2021-07-06 22:16

import App.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('p_version', models.IntegerField()),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=App.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('review', models.IntegerField()),
                ('score', models.FloatField()),
                ('price', models.FloatField()),
                ('country', models.CharField(default='Maroc', max_length=100)),
                ('city', models.CharField(default='Marrakech', max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=550)),
                ('amenities', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(default='')),
                ('datePosted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hotel')),
            ],
        ),
    ]
