# Generated by Django 3.2.4 on 2021-07-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='p_version',
            new_name='h_version',
        ),
    ]
